name: release

on:
  workflow_dispatch:
  push:
    # branches:
      # - master
  

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    uses: looker-open-source/reusable-actions/.github/workflows/marketplace-viz-release.yml@viz_workflows
    secrets: inherit